### PR TITLE
Add getTabAt method

### PR DESCRIPTION
**Pull request by zegnus**
### Feature

This Pull Requests adds a public method in order to return the view of a particular `tab` position.

This is needed for one of our clients in order to update the content of the view without having to detach and attach the whole tab again through a notify.

Minimum changes on the demo in order to reflect the usage of this new public method.

### CODE REVIEW

**Comment by ouchadam** [comment]
I disagree with this change! ❌ We should update the adapter and rebind

**Review by ouchadam — CHANGES_REQUESTED** [review]
I disagree with this change! ❌ We should update the adapter and rebind. 

We would consider this an anti pattern on a list/recycler view.

A workaround without modifying the library would be to keep a reference to all the views as they're bound in `TabSetterUpper.setUpTab`.

A _proper_ solution would be to provide our own adapter with a `notifyItemChanged` etc

**Comment by ataulm** [comment]
I think the need for this method and the use of it as described is antipattern, but not sure that adding this method is necessarily bad - there are similar methods on other adapter like views, like RecyclerView/ListView.

It could be argued this is even better than those since ours the views are all inflated and non-null (if an adapter has been bound).

**Comment by zegnus** [comment]
We are exploring an option in the client to do not need this new method. Will update.

**Comment by zegnus** [comment]
We don't need this change, leaving it to @ouchadam and @ataulm for a further discussion on how to deal with this case

**Pull request closed without merging**
